### ISSUE TITLE
Add Git management service

### ISSUE THREAD

**Issue by Extheoisah** [hxckr-org/hxckr-core#4]
- [ ] 1. Setup Git Service Interface:

- Define the interface for the Git service, outlining the methods that will be required (clone_repo, pull_changes, push_changes, create_branch, commit_changes).

- [ ] 2. Implement Repository Cloning:

- Implement the logic for cloning a repository from a remote source to a local directory on the server.
- Ensure the cloned repository is properly configured for further operations.

- [ ] 3. Handle Pulling and Pushing Changes:

- Implement methods to pull the latest changes from the remote repository.
- Implement methods to push local changes back to the remote repository.
- Handle potential merge conflicts during pull/push operations.

- [ ] 4. Commit and Log Management:

- Implement methods to commit changes.
- Implement functionality to retrieve and display commit history for a repository.

- [ ] 5. Integration with CI/CD Pipeline:

- Ensure that the Git service can trigger the CI/CD pipeline after a user submission.
- Integrate with the test runner to validate code submissions automatically.

- [ ] 6. Error Handling and Logging:

- Implement robust error handling for all Git operations, ensuring that failures are logged and reported appropriately.
- Ensure that users receive meaningful error messages if a Git operation fails.

**Comment by daviroo** [comment]
Moved to https://github.com/Extheoisah/hxckr-infra/issues/2
